# Generated by Django 6.1.1 on 2026-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_thumbnail_coursemodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='start_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
