# Generated by Django 6.1.1 on 2026-09-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_start_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursemodules',
            table='Course_Modules',
        ),
    ]
