# Generated by Django 6.1.1 on 2026-09-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_students_course_id'),
        ('courses', '0004_alter_coursemodules_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.students')),
            ],
            options={
                'db_table': 'enroll_details',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
