# Generated by Django 6.1.1 on 2026-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_last4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transactionid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
