# Generated by Django 6.1.1 on 2026-09-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_payments_card_last4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='card_last4',
            field=models.CharField(max_length=20),
        ),
    ]
