# Generated by Django 6.1.1 on 2026-09-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='pincode',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(blank=True, default=''),
        ),
    ]
