# Generated by Django 6.1.1 on 2026-09-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_students_bio_students_city_students_country_and_more'),
        ('courses', '0003_courses_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='course_id',
            field=models.ManyToManyField(to='courses.courses'),
        ),
    ]
