# Generated by Django 6.1.1 on 2026-09-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_students_course_id'),
        ('courses', '0007_alter_payments_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AddField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
