# Generated by Django 6.1.1 on 2026-09-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_students_course_id_students_course_id'),
        ('courses', '0007_alter_payments_card_last4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
