# Generated by Django 6.1.1 on 2026-09-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_students_course_id_students_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
    ]
